### ISSUE TITLE
Files in wrong location

### ISSUE THREAD

**Issue by ghost** [eddiemg10/Nyumbani#8]
Some files have been added to an inappropriate location. This is from the last pull request. Kindly find a way to place them in the right place to avoid confusion later, also for testing purposes.

![image](https://user-images.githubusercontent.com/59566139/140437172-aca31657-9b7c-49e3-8a84-f884243d3572.png)

**Comment by ghost** [comment]
Also the 'Routes.php' file.

**Comment by eddiemg10** [comment]
@Adala-Wanyande  should be fine now

**Comment by ghost** [comment]
Safe.
